name: Publish nuget
on:
  workflow_dispatch:
jobs:
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build

  pack_publish:
    name: Pack & Publish
    needs: build_test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Extract version from version.json
      run: |
        echo "VERSION=$(./.github/scripts/extract_version.sh)" >> "$GITHUB_ENV"      
    - name: Pack NuGet package
      run: dotnet pack --configuration Release --output nupkgs /p:Version=${{ env.VERSION }}
    - name: Push to NuGet
      run: dotnet nuget push "nupkgs/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key "${{ secrets.NUGET_API_KEY }}"
